# Generated by Django 5.1.6 on 2025-02-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0003_alter_book_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
    ]
