# Generated by Django 5.1.6 on 2025-02-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0005_book_author_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='catelog.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, null=True, unique=True, verbose_name='ISBN'),
        ),
    ]
