# Generated by Django 5.1.6 on 2025-02-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0007_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
