# Generated by Django 5.1.6 on 2025-04-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0015_rename_status_bookinstance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='tmp',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
