# Generated by Django 5.1.6 on 2025-04-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0016_bookinstance_tmp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_mark_returned', 'Set book as returned')]},
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='tmp',
        ),
    ]
