# Generated by Django 5.1.6 on 2025-07-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catelog', '0017_alter_bookinstance_options_remove_bookinstance_tmp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('can_create_author', 'Can create author')]},
        ),
    ]
