# Generated by Django 5.1.6 on 2025-10-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catelog", "0019_alter_author_options_alter_bookinstance_due_back"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="summary",
            field=models.TextField(
                help_text="Enter a brief description of the Author",
                max_length=1000,
                null=True,
            ),
        ),
    ]
