# Generated by Django 5.1.6 on 2025-10-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catelog", "0020_author_summary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="summary",
            new_name="about",
        ),
    ]
